hydra:
    run:
        dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
        subdir: ${hydra.job.num}

feature: ['select_cols_target_col=numerical', 'label_encode_target_col=categorical']
trainer:
  evaluation_metric: auc
  model_name: ModelXGB
  params: {
            'objective': "binary:logistic",
            "max_depth": 12,
            "learning_rate": 0.02,
            "subsample": 0.8,
            "colsample_bytree": 0.4,
            "missing": -1,
            "eval_metric": "auc",
            "tree_method": "hist",
            "num_round": 10,
            "early_stopping_rounds": 5
        }
  cols_definition:
    target_col: 'Survived'
    categorical_col: [
      'Pclass_label_encode',  'Sex_label_encode',  'Cabin_label_encode',  'Embarked_label_encode'
    ]
